export enum GameEventType {
	ParticipantJoined = "ParticipantJoined",
	ParticipantLeft = "ParticipantLeft",
	TicketAdded = "TicketAdded",
	TicketUpdated = "TicketUpdated",
	TicketDeleted = "TicketDeleted",
	Reconnecting = "Reconnecting",
	Reconnected = "Reconnected",
	Disconnected = "Disconnected",
	VotingStarted = "VotingStarted",
	CardsRevealed = "CardsRevealed",
	VotingFinished = "VotingFinished",
	ParticipantVoted = "ParticipantVoted",
	SettingsUpdated = "SettingsUpdated",
	CurrentParticipantUpdated = "CurrentParticipantUpdated",
	NewEstimationApplied = "NewEstimationApplied",
}
