export enum GameEventType {
	ParticipantJoined = "ParticipantJoined",
	ParticipantLeft = "ParticipantLeft",
	TicketAdded = "TicketAdded",
	TicketUpdated = "TicketUpdated",
	TicketDeleted = "TicketDeleted",
	ConnectionEvent = "ConnectionEvent",
	VotingStarted = "VotingStarted",
	CardsRevealed = "CardsRevealed",
	VotingCancelled = "VotingCancelled",
	VotingFinished = "VotingFinished",
	ParticipantVoted = "ParticipantVoted",
	SettingsUpdated = "SettingsUpdated",
	CurrentParticipantUpdated = "CurrentParticipantUpdated",
	NewEstimationApplied = "NewEstimationApplied",
}
