// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokerPlanning.Infrastructure.src.Persistence;

#nullable disable

namespace PokerPlanning.Infrastructure.Migrations
{
    [DbContext(typeof(PokerPlanningDbContext))]
    [Migration("20231112120004_Add_VotingSystem_DefaultData")]
    partial class Add_VotingSystem_DefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.VotingSystemAggregate.Entities.VotingSystemVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("VotingSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingSystemId");

                    b.ToTable("VotingSystemVotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf0d4051-84a7-4162-8f48-580d4e488df2"),
                            Order = 0m,
                            Suit = "🏖️",
                            Value = "0",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("5addfe74-4e6d-4dde-8c1b-01b856a57b2a"),
                            Order = 1m,
                            Suit = "⚡",
                            Value = "1",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("f1f6b021-7f60-4b21-b297-6be2b93f0cb9"),
                            Order = 2m,
                            Suit = "🚀",
                            Value = "2",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("a05dcc39-4781-4407-9255-94d8cc847657"),
                            Order = 3m,
                            Suit = "🤔",
                            Value = "3",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("9875f3f1-cbb0-40ee-b649-de48b706b7ba"),
                            Order = 4m,
                            Suit = "😬",
                            Value = "5",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("8d23dd52-a81e-41b5-a9ac-2df12cd6d667"),
                            Order = 5m,
                            Suit = "😵",
                            Value = "8",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("07746553-c20a-4337-9fea-d37d9a473e78"),
                            Order = 6m,
                            Suit = "☠️",
                            Value = "13",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("2c60634e-02ae-4b06-9894-c4f928d3037b"),
                            Order = 7m,
                            Suit = "🤡",
                            Value = "?",
                            VotingSystemId = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c")
                        },
                        new
                        {
                            Id = new Guid("66de38f8-1e99-4e39-9eef-ceeff15dd938"),
                            Order = 0m,
                            Suit = "🏖️",
                            Value = "xss",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("c5a7d8f5-432a-447a-81f6-9870e07e237a"),
                            Order = 1m,
                            Suit = "⚡",
                            Value = "xs",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("46d6301b-4fc9-4e78-a797-891592197821"),
                            Order = 2m,
                            Suit = "🚀",
                            Value = "s",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("3c25140f-c8fb-409f-b54d-04835c143319"),
                            Order = 3m,
                            Suit = "🤔",
                            Value = "m",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("ee166192-1c6d-4e8a-81d2-b111a0ec0a6b"),
                            Order = 4m,
                            Suit = "😬",
                            Value = "l",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("46c84b9b-a443-4ac3-8550-02d63c57c6d7"),
                            Order = 5m,
                            Suit = "😵",
                            Value = "xl",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("0bc7aa91-6a87-4386-994d-105fb13b6d98"),
                            Order = 6m,
                            Suit = "☠️",
                            Value = "xxl",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        },
                        new
                        {
                            Id = new Guid("28e4cc55-2acf-4138-b781-8ae4da22582a"),
                            Order = 7m,
                            Suit = "🤡",
                            Value = "?",
                            VotingSystemId = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480")
                        });
                });

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.VotingSystemAggregate.VotingSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("VotingSystems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a113d25-34c9-4b49-985c-2df6dd67650c"),
                            Name = "Fibonacci"
                        },
                        new
                        {
                            Id = new Guid("8eccd01f-53e5-4e6f-8553-64c81448a480"),
                            Name = "T-shirts"
                        });
                });

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.VotingSystemAggregate.Entities.VotingSystemVote", b =>
                {
                    b.HasOne("PokerPlanning.Domain.src.Models.VotingSystemAggregate.VotingSystem", null)
                        .WithMany("Votes")
                        .HasForeignKey("VotingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.VotingSystemAggregate.VotingSystem", b =>
                {
                    b.HasOne("PokerPlanning.Domain.src.Models.UserAggregate.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PokerPlanning.Domain.src.Models.VotingSystemAggregate.VotingSystem", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
