name: Playwright Tests
on:
    pull_request:
        branches:
            - "*"

    workflow_call:
        inputs:
            update-snapshots:
                description: "Update Shanpshots?"
                type: boolean

    workflow_dispatch:
        inputs:
            update-snapshots:
                description: "Update Shanpshots?"
                type: boolean
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        env:
            CI: true
            BROWSERCAT_API_KEY: ${{ secrets.BROWSERCAT_API_KEY }}

        steps:
            - uses: actions/checkout@v4
              name: Checkout Repo

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - uses: actions/cache@v4
              id: pnpm-cache
              with:
                  path: ~/.pnpm-store
                  key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

            - run: pnpm install
              name: Install modules from pnpm

            - name: Set up the Snapshot cache
              id: snapshot-cache
              uses: actions/cache@v4
              with:
                  key: cache/${{github.repository}}/${{github.ref}}
                  restore-keys: cache/${{github.repository}}/refs/heads/master
                  path: ./e2e/snapshots/**

            - name: Initialize snapshots
              if: ${{steps.snapshot-cache.outputs.cache-hit != 'true' || inputs.update-snapshots == 'true'}}
              run: npx playwright test --update-snapshots --reporter html

            - name: Run Playwright tests
              run: pnpm exec playwright test

            - name: Upload test report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: ./e2e/results
                  retention-days: 30
                  overwrite: true
